version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bank-rest-db-dev
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bank_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: bank-rest-app-dev
    image: maven:3.9-eclipse-temurin-17
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    working_dir: /app

    ports:
      - "8081:8081"
      - "5005:5005"

    depends_on:
      db:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bank_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      APP_SECURITY_JWT_SECRET: ${JWT_SECRET}
      APP_ENCRYPTION_AES_KEY: ${ENCRYPTION_KEY}

    command: >
      mvn spring-boot:run 
        -Dspring-boot.run.jvmArguments="
          -Dspring.devtools.restart.poll-interval=3s 
          -Dspring.devtools.restart.quiet-period=2s 
          -Djava.security.egd=file:/dev/./urandom
          -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
        "

volumes:
  postgres-data-dev: